apiVersion: v1
kind: Service
metadata:
  name: travel-frontend
spec:
  selector:
    app: travel-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  type: ClusterIP
